"""add dispatch_patterns and dispatch_reject_rules tables

Revision ID: 807c09468d8a
Revises: f84732e3ff7b
Create Date: 2026-08-05 21:45:26.666933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '807c09468d8a'
down_revision: Union[str, None] = 'f84732e3ff7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispatch_patterns',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('flow', sa.Text(), nullable=False),
    sa.Column('pattern', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), server_default='100', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('match_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_matched_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('dispatch_patterns_flow_idx', 'dispatch_patterns', ['flow', 'enabled', 'priority'], unique=False)
    op.create_table('dispatch_reject_rules',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('flow', sa.Text(), nullable=False),
    sa.Column('pattern', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('veto_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_matched_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('dispatch_reject_rules_flow_idx', 'dispatch_reject_rules', ['flow', 'enabled'], unique=False)
    # ### end Alembic commands ###

    # Seed today's hardcoded services/kv_notes.py constants verbatim — behavior-neutral
    # cutover, nothing regresses on the switch to DB-backed patterns. created_by left NULL:
    # a real admin Telegram ID must never land in committed migration history (same call
    # already made for db/models.py:User's no-FK-to-Entry note).
    dispatch_patterns = sa.table(
        'dispatch_patterns',
        sa.column('flow', sa.Text),
        sa.column('pattern', sa.Text),
        sa.column('priority', sa.Integer),
        sa.column('note', sa.Text),
    )
    op.bulk_insert(dispatch_patterns, [
        {
            'flow': 'save',
            'pattern': r"^(?:save|remember)\s+(?P<key>.+?)\s*(?:\bas\b|\bis\b|\bto\b|:\s+|=\s+)(?P<value>.+)$",
            'priority': 100,
            'note': (
                "Key always comes first (\"save my linkedin profile: URL\" / \"... as URL\" / "
                "\"... is URL\") - tried treating \"as\" as reversed (file-save convention), but "
                "real testing showed key-first matches actual usage for every separator. "
                "\":\"/\"=\" must be followed by whitespace, otherwise a URL's own \"https:\" or "
                "a query string's \"?x=1\" gets misread as the separator."
            ),
        },
        {
            'flow': 'get',
            'pattern': r"^what(?:'s|\s+is)\s+(?P<key>.+?)\??$",
            'priority': 100,
            'note': 'Original GET_PATTERN from services/kv_notes.py.',
        },
    ])

    dispatch_reject_rules = sa.table(
        'dispatch_reject_rules',
        sa.column('flow', sa.Text),
        sa.column('pattern', sa.Text),
        sa.column('note', sa.Text),
    )
    op.bulk_insert(dispatch_reject_rules, [
        {
            'flow': 'save',
            'pattern': r'^(?:this|that|it)$',
            'note': (
                "A key that's JUST a bare pronoun (\"save this as ...\") is almost always a "
                "parsing artifact of a run-on sentence with no real separator between a filler "
                "word and the intended label, not a genuine intended key. Found live: "
                "\"save this as my linked profile <url>\" was wrongly saving key=\"this\"."
            ),
        },
    ])

    # LISTEN/NOTIFY cache invalidation: any change to either table (via the admin command,
    # or a direct psql edit) broadcasts to every listening arq worker process, so the
    # in-memory pattern cache refreshes without needing a restart. Notifications aren't
    # durable (a listener that's briefly down misses them) — services/dispatch_patterns.py
    # also does a periodic fallback reload as a safety net, so a missed notification only
    # delays a pickup, never loses it permanently.
    op.execute("""
        CREATE OR REPLACE FUNCTION notify_dispatch_patterns_change() RETURNS trigger AS $$
        BEGIN
            PERFORM pg_notify('dispatch_patterns_changed', TG_TABLE_NAME);
            RETURN NULL;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER dispatch_patterns_notify
        AFTER INSERT OR UPDATE OR DELETE ON dispatch_patterns
        FOR EACH STATEMENT EXECUTE FUNCTION notify_dispatch_patterns_change();
    """)
    op.execute("""
        CREATE TRIGGER dispatch_reject_rules_notify
        AFTER INSERT OR UPDATE OR DELETE ON dispatch_reject_rules
        FOR EACH STATEMENT EXECUTE FUNCTION notify_dispatch_patterns_change();
    """)


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS dispatch_reject_rules_notify ON dispatch_reject_rules")
    op.execute("DROP TRIGGER IF EXISTS dispatch_patterns_notify ON dispatch_patterns")
    op.execute("DROP FUNCTION IF EXISTS notify_dispatch_patterns_change()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('dispatch_reject_rules_flow_idx', table_name='dispatch_reject_rules')
    op.drop_table('dispatch_reject_rules')
    op.drop_index('dispatch_patterns_flow_idx', table_name='dispatch_patterns')
    op.drop_table('dispatch_patterns')
    # ### end Alembic commands ###
