"""entries and entry_events

Revision ID: ff4f4e539287
Revises: 87611d1aa43d
Create Date: 2026-07-26 00:15:07.329483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff4f4e539287'
down_revision: Union[str, None] = '87611d1aa43d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # HLD section 4 extensions — not part of SQLAlchemy metadata, autogenerate can't see these.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.Enum('office_work', 'self_learning', 'personal', 'ideas', name='entry_category'), nullable=False),
    sa.Column('kind', sa.Enum('note', 'task', name='entry_kind'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'done', 'archived', name='entry_status'), server_default='open', nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('source_msg_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('search_tsv', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('english', coalesce(title, '')), 'A') || setweight(to_tsvector('english', coalesce(body, '')), 'B')", persisted=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('entries_embed_idx', 'entries', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('entries_lookup_idx', 'entries', ['user_id', 'status', 'category', 'due_at'], unique=False)
    op.create_index('entries_tags_idx', 'entries', ['tags'], unique=False, postgresql_using='gin')
    op.create_index('entries_tsv_idx', 'entries', ['search_tsv'], unique=False, postgresql_using='gin')
    op.create_table('entry_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('entry_id', sa.UUID(), nullable=False),
    sa.Column('event', sa.Enum('created', 'updated', 'completed', 'reopened', 'archived', name='event_type'), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('source_msg_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('entry_events_entry_idx', 'entry_events', ['entry_id', 'created_at'], unique=False)
    # ### end Alembic commands ###

    # D8: the search surface. Today it wraps one table; later phases UNION more in.
    # services/search.py (Phase 4) queries this view, never `entries` directly.
    op.execute("""
        CREATE VIEW searchable_items AS
        SELECT
          id,
          user_id,
          'notes'::text AS source,
          title,
          body,
          embedding,
          search_tsv,
          status::text AS status,
          category::text AS category,
          due_at,
          created_at,
          updated_at
        FROM entries
        WHERE status <> 'archived'
    """)


def downgrade() -> None:
    op.execute("DROP VIEW IF EXISTS searchable_items")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('entry_events_entry_idx', table_name='entry_events')
    op.drop_table('entry_events')
    op.drop_index('entries_tsv_idx', table_name='entries', postgresql_using='gin')
    op.drop_index('entries_tags_idx', table_name='entries', postgresql_using='gin')
    op.drop_index('entries_lookup_idx', table_name='entries')
    op.drop_index('entries_embed_idx', table_name='entries', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('entries')
    # ### end Alembic commands ###
